In [17]:
import numpy as np

In [19]:
from scipy.stats import multivariate_normal as mvn

In [34]:
from tools import methons
methons.debug()

(array([3. , 5.5]),
 array([[ 8. , 14. ],
        [14. , 24.5]]))

In [16]:
norm.pdf(a,mean,cov_mat)

array([[0.48394145, 0.48394145, 0.48394145, 0.48394145, 0.48394145,
        0.48394145],
       [0.48394145, 0.48394145, 0.48394145, 0.48394145, 0.48394145,
        0.48394145],
       [0.48394145, 0.48394145, 0.48394145, 0.48394145, 0.48394145,
        0.48394145],
       [0.48394145, 0.48394145, 0.48394145, 0.48394145, 0.48394145,
        0.48394145],
       [0.48394145, 0.48394145, 0.48394145, 0.48394145, 0.48394145,
        0.48394145],
       [0.48394145, 0.48394145, 0.48394145, 0.48394145, 0.48394145,
        0.48394145]])